// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtwfPpmL-HAE2LKDw2qs0xmyndAeMtuPA',
    appId: '1:611204246163:web:6115366a15716a9fc33b66',
    messagingSenderId: '611204246163',
    projectId: 'mc-space-platform',
    authDomain: 'mc-space-platform.firebaseapp.com',
    storageBucket: 'mc-space-platform.firebasestorage.app',
    measurementId: 'G-QY7F55FNFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo1Obam-PmTJrb8XsRt_FayYevPfIXcwg',
    appId: '1:611204246163:android:0e595476e0a9b32bc33b66',
    messagingSenderId: '611204246163',
    projectId: 'mc-space-platform',
    storageBucket: 'mc-space-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0hpjZ-GJUWyGbdSnkfpMMML5hgd4laiA',
    appId: '1:611204246163:ios:d40af277e37fc2d8c33b66',
    messagingSenderId: '611204246163',
    projectId: 'mc-space-platform',
    storageBucket: 'mc-space-platform.firebasestorage.app',
    androidClientId: '611204246163-5b1sf1h9uqmh0vvjnlapu1noesvh6dmi.apps.googleusercontent.com',
    iosClientId: '611204246163-2eoa3e412d6ntcehqjgain9iia0u5tmp.apps.googleusercontent.com',
    iosBundleId: 'com.mcspace.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0hpjZ-GJUWyGbdSnkfpMMML5hgd4laiA',
    appId: '1:611204246163:ios:b7488a9bc616e81dc33b66',
    messagingSenderId: '611204246163',
    projectId: 'mc-space-platform',
    storageBucket: 'mc-space-platform.firebasestorage.app',
    androidClientId: '611204246163-5b1sf1h9uqmh0vvjnlapu1noesvh6dmi.apps.googleusercontent.com',
    iosClientId: '611204246163-eefs5qqvh7mto0joo96dtb0gsghi9dd1.apps.googleusercontent.com',
    iosBundleId: 'com.mcspace.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtwfPpmL-HAE2LKDw2qs0xmyndAeMtuPA',
    appId: '1:611204246163:web:a521014203b606d4c33b66',
    messagingSenderId: '611204246163',
    projectId: 'mc-space-platform',
    authDomain: 'mc-space-platform.firebaseapp.com',
    storageBucket: 'mc-space-platform.firebasestorage.app',
    measurementId: 'G-NCMM533H6J',
  );

}